---
# tasks file for nginx-role
- name: Install epel + Nginx
  become: true
  block:
    - name: Nginx | Install eper-release
      ansible.builtin.yum:
        name:
          - epel-release
        state: present
    - name: Nginx | Install Nginx
      ansible.builtin.yum:
        name:
          - nginx
        state: present
      notify: Start nginx
    - name: Nginx | Create general config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: Reload nginx
    - name: install git
      ansible.builtin.yum:
        name: git
        state: present
