---
# handlers file for nginx-role
- name: Start nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
- name: Reload nginx
  become: true
  ansible.builtin.command: nginx -s reload
